// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

#version 460
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_ray_query : require
#ifdef USE_BARYCENTRIC
/* Compiled into the mesh_bary.frag.spv variant (when the device supports
 * VK_KHR_fragment_shader_barycentric) so Ptex triangle-corner colors are
 * interpolated per pixel like the RT path, not flat-averaged. */
#extension GL_EXT_fragment_shader_barycentric : require
#endif

/* Material data — same struct as raytrace.rchit.glsl's MaterialData
 * (and GpuMaterialParams in gpu.h). Only the fields we use in raster
 * are tagged with comments; the rest pad the std430 layout. */
struct MaterialData {
    vec4  base_color;
    vec4  emissive_color;
    float metallic;
    float roughness;
    float opacity;
    float ior;
    float occlusion;
    float clearcoat;
    float clearcoat_roughness;
    float normal_scale;
    ivec4 tex_indices_a;       // diffuse, normal, roughness, metallic
    ivec4 tex_indices_b;       // emissive, occlusion, opacity, displacement
    int   use_vertex_color;
    float udim_scale_u;
    float udim_scale_v;
    float opacity_threshold;
    vec4  subsurface_color;
    vec4  subsurface_radius;
    vec4  transmission_color;
    float subsurface_weight;
    float subsurface_scale;
    float transmission_weight;
    float transmission_ior;
    int   tex_subsurface_weight;
    int   tex_transmission_weight;
    int   sss_color_authored;
    int   use_specular_workflow;
    vec4  specular_color;
    vec4  normal_tex_scale;
    vec4  normal_tex_bias;
    vec4  mdl_uv_transform;
    int   v_flip;
    float roughness_tex_scale;
    float roughness_tex_bias;
    int   _pad_v_flip;
};

layout(set = 0, binding = 0, std430) readonly buffer MaterialBuffer {
    MaterialData materials[];
};

layout(set = 0, binding = 1) uniform sampler2D matTextures[];

/* IBL textures, same bindings the rchit uses on the descriptor set
 * (gpu_vulkan.c lines 9101-9117). When pc.ibl_params.x == 0 these are
 * placeholder samplers and we fall back to procedural sky/ground. */
layout(set = 0, binding = 2) uniform sampler2D envMap;
layout(set = 0, binding = 3) uniform sampler2D brdfLUT;
layout(set = 0, binding = 4) uniform sampler2D irrMap;
layout(set = 0, binding = 5) uniform accelerationStructureEXT tlas;

#define LIGHT_KIND_RECT     0
#define LIGHT_KIND_DISTANT  1
#define LIGHT_KIND_SPHERE   2

struct GpuLight {
    vec3  position;   float intensity;
    vec3  normal;     int   kind;
    vec3  u_axis;     int   normalize;
    vec3  v_axis;     float angle_deg;
    vec3  color;      float _pad;
};

layout(set = 0, binding = 6, std430) readonly buffer LightsBuffer {
    int       nlights;
    int       _lpad[3];
    GpuLight  items[];
} sceneLights;

layout(set = 0, binding = 7, std430) readonly buffer PtexTriangleColors {
    uint colors[];
} ptexTriColors;

layout(push_constant) uniform PushConstants {
    mat4 mvp;
    mat4 model;
    vec4 color;
    vec4 eye_pos;
    vec4 ibl_params;  /* x=has_ibl, y=mip_levels, z=intensity */
    vec4 tone_params; /* x=surface exposure scale, y=sky exposure scale */
} pc;

/* Equirectangular UV from a world-space direction. Up-axis aware to match the
 * RT path (raytrace.rmiss/rchit dirToEquirect) — the env/irradiance maps are
 * baked in equirect and the sampling direction must account for the scene up
 * axis, else a Y-up scene (e.g. Moana) samples surface diffuse/specular IBL
 * from the wrong part of the map (a scene-wide color/tint mismatch vs RT).
 * The up axis is packed into tone_flags bits 24-25 (set per-draw by the
 * renderer); the Z-up branch is bit-identical to the old hardcoded version so
 * existing Z-up scenes are unchanged. */
vec2 dirToEquirect(vec3 dir) {
    const float kPI = 3.14159265;
    const float kDomeLongitudeOffset = 340.0 / 360.0;
    uint upAxis = (floatBitsToUint(pc.tone_params.w) >> 24) & 3u;
    float u, v;
    if (upAxis == 1u) {            // Y-up (USD default)
        u = fract(atan(dir.x, dir.z) * (0.5 / kPI) + 0.5 + kDomeLongitudeOffset);
        v = asin(clamp(dir.y, -1.0, 1.0)) * (1.0 / kPI) + 0.5;
    } else if (upAxis == 0u) {     // X-up
        u = fract(atan(dir.y, dir.z) * (0.5 / kPI) + 0.5 + kDomeLongitudeOffset);
        v = asin(clamp(dir.x, -1.0, 1.0)) * (1.0 / kPI) + 0.5;
    } else {                       // Z-up (== legacy hardcoded path)
        u = fract(atan(dir.x, dir.y) * (0.5 / kPI) + 0.5 + kDomeLongitudeOffset);
        v = asin(clamp(dir.z, -1.0, 1.0)) * (1.0 / kPI) + 0.5;
    }
    return vec2(u, 1.0 - v);
}

/* Split-sum specular IBL term. brdfLUT is generated by gpu_vulkan.c from
 * a GGX importance-sampled integration, matching the OpenGL raster path. */
vec3 sampleEnvBRDF(vec3 F0, float roughness, float NdotV) {
    vec2 brdf = texture(brdfLUT, vec2(clamp(abs(NdotV), 0.0, 1.0),
                                      clamp(roughness, 0.0, 1.0))).rg;
    return F0 * brdf.x + brdf.y;
}

float traceContactVisibility(vec3 origin, vec3 direction, float tmax) {
    rayQueryEXT rq;
    rayQueryInitializeEXT(rq, tlas,
        gl_RayFlagsTerminateOnFirstHitEXT | gl_RayFlagsOpaqueEXT,
        0xFF, origin, 0.001, direction, tmax);
    while (rayQueryProceedEXT(rq)) {}
    return (rayQueryGetIntersectionTypeEXT(rq, true)
            == gl_RayQueryCommittedIntersectionNoneEXT) ? 1.0 : 0.0;
}

vec3 ptexTriangleColor(uint offset) {
    if (offset == 0xFFFFFFFFu)
        return vec3(-1.0);
    uint base = offset + uint(gl_PrimitiveID) * 3u;
    vec3 c0 = unpackUnorm4x8(ptexTriColors.colors[base + 0u]).rgb;
    vec3 c1 = unpackUnorm4x8(ptexTriColors.colors[base + 1u]).rgb;
    vec3 c2 = unpackUnorm4x8(ptexTriColors.colors[base + 2u]).rgb;
#ifdef USE_BARYCENTRIC
    /* Per-pixel barycentric blend of the three corners — matches RT's
     * closest-hit interpolation; gl_BaryCoordEXT components map to the
     * triangle's vertices in index order, the same order the corner colors
     * were packed (gl_PrimitiveID*3 + {0,1,2}). */
    vec3 bc = gl_BaryCoordEXT;
    return c0 * bc.x + c1 * bc.y + c2 * bc.z;
#else
    return (c0 + c1 + c2) * (1.0 / 3.0);
#endif
}

float contactVisibility(vec3 worldPos, vec3 N) {
    vec3 helper = (abs(N.y) < 0.95) ? vec3(0.0, 1.0, 0.0) : vec3(1.0, 0.0, 0.0);
    vec3 T = normalize(cross(helper, N));
    vec3 B = cross(N, T);
    vec3 origin = worldPos + N * 0.001;
    float v = 0.0;
    v += traceContactVisibility(origin, N, 0.140);
    v += traceContactVisibility(origin, normalize(N * 0.62 + T * 0.60), 0.320);
    v += traceContactVisibility(origin, normalize(N * 0.62 - T * 0.60), 0.320);
    v += traceContactVisibility(origin, normalize(N * 0.62 + B * 0.60), 0.320);
    v += traceContactVisibility(origin, normalize(N * 0.62 - B * 0.60), 0.320);
    return v * 0.2;
}

vec3 fresnelSchlickRoughness(float NdotV, vec3 F0, float roughness) {
    float k = 1.0 - roughness;
    return F0 + (max(vec3(k), F0) - F0) * pow(1.0 - NdotV, 5.0);
}

/* Cheap ACES filmic tonemap — same constants the rchit ACES pass uses.
 * Only applied on the IBL branch so the existing procedural-ambient
 * scenes render bit-stable (no implicit gamma shift on chess etc.). */
vec3 acesFilmic(vec3 x) {
    const float a = 2.51, b = 0.03, c = 2.43, d = 0.59, e = 0.14;
    return clamp((x * (a * x + b)) / (x * (c * x + d) + e), 0.0, 1.0);
}

layout(location = 0) in vec3 fragWorldPos;
layout(location = 1) in vec3 fragNormal;
layout(location = 2) in vec3 fragColor;
layout(location = 3) in vec2 fragUV;
layout(location = 5) flat in vec3 fragEyePos;

layout(location = 0) out vec4 outColor;

/* Pixar branchless ONB — derives a stable orthonormal basis (T, B) from
 * a world-space normal so we can project a tangent-space normal map back
 * into world space without per-vertex tangent inputs. Same construction
 * as raytrace.rchit.glsl uses for the rchit's normal-map sampling. */
void branchlessONB(vec3 n, out vec3 t, out vec3 b) {
    float sign_ = (n.z >= 0.0) ? 1.0 : -1.0;
    float a = -1.0 / (sign_ + n.z);
    float bv = n.x * n.y * a;
    t = vec3(1.0 + sign_ * n.x * n.x * a, sign_ * bv, -sign_ * n.x);
    b = vec3(bv, sign_ + n.y * n.y * a, -n.y);
}

/* GGX micro-facet distribution. Same form as raytrace.rchit.glsl's
 * distributionGGX — alpha = roughness² is the standard Disney/Karis
 * convention so chess-set roughness values render comparably across
 * RT and raster. */
float distributionGGX(vec3 N, vec3 H, float roughness) {
    float a = roughness * roughness;
    float a2 = a * a;
    float NdotH = max(dot(N, H), 0.0);
    float NdotH2 = NdotH * NdotH;
    float denom = NdotH2 * (a2 - 1.0) + 1.0;
    return a2 / (3.14159265 * denom * denom + 1e-6);
}

/* Schlick-GGX geometric occlusion (combined Smith term). */
float geometrySmithSchlick(vec3 N, vec3 V, vec3 L, float roughness) {
    float r = (roughness + 1.0);
    float k = (r * r) / 8.0;
    float NdotV = max(dot(N, V), 0.0);
    float NdotL = max(dot(N, L), 0.0);
    float Gv = NdotV / (NdotV * (1.0 - k) + k);
    float Gl = NdotL / (NdotL * (1.0 - k) + k);
    return Gv * Gl;
}

vec3 fresnelSchlick(float HdotV, vec3 F0) {
    return F0 + (1.0 - F0) * pow(1.0 - HdotV, 5.0);
}

vec3 evalDirectBRDF(vec3 L, vec3 N, vec3 V, vec3 albedo,
                    float metallic, float roughness, vec3 F0, float NdotV) {
    float NdotL = max(dot(N, L), 0.0);
    if (NdotL <= 0.0) return vec3(0.0);

    vec3 H = normalize(V + L);
    float D = distributionGGX(N, H, roughness);
    float G = geometrySmithSchlick(N, V, L, roughness);
    vec3  F = fresnelSchlickRoughness(max(dot(H, V), 0.0), F0, roughness);
    vec3  spec = (D * G * F) / (4.0 * NdotV * NdotL + 1e-4);
    vec3  kS = F;
    vec3  kD = (vec3(1.0) - kS) * (1.0 - metallic);
    return (kD * albedo / 3.14159265 + spec) * NdotL;
}

float areaLightSpecularRoughness(float roughness, float angularDiameter) {
    float a = clamp(angularDiameter * 2.5, 0.0, 1.0);
    return clamp(sqrt(roughness * roughness + a * a), roughness, 1.0);
}

vec3 evalSceneRectLightSample(GpuLight light, vec3 samplePos, float radiance,
                              float area, vec3 N, vec3 V, vec3 albedo,
                              float metallic, float roughness, vec3 F0,
                              vec3 worldPos, float NdotV) {
    vec3 toLight = samplePos - worldPos;
    float dist2 = dot(toLight, toLight);
    if (dist2 < 1e-4) return vec3(0.0);
    float dist = sqrt(dist2);
    vec3 L = toLight / dist;

    float cosLight = dot(-L, light.normal);
    if (cosLight <= 0.0) return vec3(0.0);

    float geom = (cosLight * area) / max(dist2, 1e-4);
    float shadow = 1.0;
    if (pc.ibl_params.w > 0.25) {
        shadow = traceContactVisibility(worldPos + N * 0.01, L, dist * 0.999);
        if (shadow <= 0.0) return vec3(0.0);
    }
    /* The rect is sampled as a few point lights; widen the specular lobe by
     * emitter angular diameter so rough floors do not get point-light glints. */
    float rectAngular = clamp(2.0 * max(length(light.u_axis), length(light.v_axis)) /
                              max(dist, 1e-3), 0.0, 1.0);
    float specRoughness = areaLightSpecularRoughness(roughness, rectAngular);
    return evalDirectBRDF(L, N, V, albedo, metallic, specRoughness, F0, NdotV) *
           (light.color * radiance) * geom * shadow;
}

vec3 evalSceneLight(GpuLight light, vec3 N, vec3 V, vec3 albedo,
                    float metallic, float roughness, vec3 F0,
                    vec3 worldPos, float NdotV) {
    if (light.kind == LIGHT_KIND_RECT) {
        float area = 4.0 * length(light.u_axis) * length(light.v_axis);
        float radiance = (light.normalize != 0)
            ? light.intensity / max(area * 3.14159265, 1e-6)
            : light.intensity / 3.14159265;
        radiance *= 0.0012;

        /* 3x3 Gauss-Legendre quadrature over the rectangular emitter.
         * The weights sum to one because evalSceneRectLightSample already
         * multiplies by the full light area. */
        const float q = 0.7745966692;
        const float wc = 0.1975308642;
        const float we = 0.1234567901;
        const float wk = 0.0771604938;
        vec3 accum = vec3(0.0);
        vec3 center = light.position;
        vec3 U = light.u_axis;
        vec3 W = light.v_axis;
        accum += evalSceneRectLightSample(light, center, radiance, area,
                                          N, V, albedo, metallic, roughness, F0,
                                          worldPos, NdotV) * wc;
        accum += evalSceneRectLightSample(light, center + U * q, radiance, area,
                                          N, V, albedo, metallic, roughness, F0,
                                          worldPos, NdotV) * we;
        accum += evalSceneRectLightSample(light, center - U * q, radiance, area,
                                          N, V, albedo, metallic, roughness, F0,
                                          worldPos, NdotV) * we;
        accum += evalSceneRectLightSample(light, center + W * q, radiance, area,
                                          N, V, albedo, metallic, roughness, F0,
                                          worldPos, NdotV) * we;
        accum += evalSceneRectLightSample(light, center - W * q, radiance, area,
                                          N, V, albedo, metallic, roughness, F0,
                                          worldPos, NdotV) * we;
        accum += evalSceneRectLightSample(light, center + U * q + W * q,
                                          radiance, area, N, V, albedo, metallic,
                                          roughness, F0, worldPos, NdotV) * wk;
        accum += evalSceneRectLightSample(light, center + U * q - W * q,
                                          radiance, area, N, V, albedo, metallic,
                                          roughness, F0, worldPos, NdotV) * wk;
        accum += evalSceneRectLightSample(light, center - U * q + W * q,
                                          radiance, area, N, V, albedo, metallic,
                                          roughness, F0, worldPos, NdotV) * wk;
        accum += evalSceneRectLightSample(light, center - U * q - W * q,
                                          radiance, area, N, V, albedo, metallic,
                                          roughness, F0, worldPos, NdotV) * wk;
        return accum;
    } else if (light.kind == LIGHT_KIND_DISTANT) {
        vec3 L = normalize(-light.normal);
        float shadow = 1.0;
        if (pc.ibl_params.w > 0.25) {
            shadow = traceContactVisibility(worldPos + N * 0.01, L, 100000.0);
            if (shadow <= 0.0) return vec3(0.0);
        }
        return evalDirectBRDF(L, N, V, albedo, metallic, roughness, F0, NdotV) *
               light.color * (light.intensity * 0.00165) * shadow;
    } else if (light.kind == LIGHT_KIND_SPHERE) {
        vec3 toLight = light.position - worldPos;
        float dist2 = max(dot(toLight, toLight), 1e-4);
        float dist = sqrt(dist2);
        vec3 L = toLight / dist;
        float radius = max(light.u_axis.x, 1e-4);
        float area = 4.0 * 3.14159265 * radius * radius;
        float radiance = (light.normalize != 0) ? light.intensity / area
                                                : light.intensity;
        /* Small no-HDR probe SphereLights need a lower radiance scale than
         * DistantLights; otherwise high-albedo USDZ assets blow out long
         * before OVRTX's auto-exposure settles. */
        radiance *= 0.00013;
        float shadow = 1.0;
        if (pc.ibl_params.w > 0.25) {
            shadow = traceContactVisibility(worldPos + N * 0.01, L,
                                            max(dist - radius, 0.01));
            if (shadow <= 0.0) return vec3(0.0);
        }
        float sphereAngular = clamp(2.0 * radius / max(dist, 1e-3), 0.0, 1.0);
        float specRoughness = areaLightSpecularRoughness(roughness, sphereAngular);
        return evalDirectBRDF(L, N, V, albedo, metallic, specRoughness, F0, NdotV) *
               light.color * radiance * shadow / dist2;
    }
    return vec3(0.0);
}

void main() {
    vec3 N = normalize(fragNormal);

    /* ---- Material albedo + scalar params ---- */
    /* Default: per-vertex/per-mesh fragColor (USD displayColor). The
     * material slot overrides only when use_vertex_color == 0, matching
     * the RT shader. The placeholder material (uploaded for descriptor
     * wiring when scene has no UsdShade materials) has use_vertex_color=1
     * so this branch keeps fragColor as the albedo. */
vec3  albedo    = fragColor;
float metallic  = 0.0;
float roughness = 0.5;
float alpha     = 1.0;
float matIor    = 1.5;
float clearcoat = 0.0;
float clearcoatRoughness = 0.04;
float transWeight = 0.0;
vec3  transTint = vec3(1.0);
float transIor  = 1.5;
float sssWeight = 0.0;
vec3  sssColor  = vec3(1.0);
vec3  emissive  = vec3(0.0);
float ao        = 1.0;
int   opacityThresholdActive = 0;
float opacityThreshold = 0.0;
int   useSpecularWorkflow = 0;
vec3  specularColor = vec3(0.04);
bool  materialUsesVertexColor = true;
    /* Material id now arrives per-instance via the push constant (eye_pos.w as
     * int bits) instead of the per-vertex matID attribute, so content-hash
     * dedup can share one geometry across materials. Clamped >=0 on the CPU to
     * match the legacy per-vertex value bit-for-bit. */
    int fragMatID = floatBitsToInt(pc.eye_pos.w);
    if (fragMatID >= 0) {
        MaterialData m = materials[nonuniformEXT(fragMatID)];
        vec2 tc = fragUV / vec2(max(m.udim_scale_u, 1e-6),
                                 max(m.udim_scale_v, 1e-6));
        tc = tc * m.mdl_uv_transform.xy + m.mdl_uv_transform.zw;
        if (m.v_flip != 0) tc.y = 1.0 - tc.y;
        materialUsesVertexColor = (m.use_vertex_color != 0);
    if (m.use_vertex_color == 0) {
        albedo = m.base_color.rgb;
    }
    metallic  = m.metallic;
    roughness = m.roughness;
    alpha     = m.base_color.a * m.opacity;
    matIor    = m.ior;
    clearcoat = m.clearcoat;
    clearcoatRoughness = clamp(m.clearcoat_roughness, 0.04, 1.0);
    transWeight = m.transmission_weight;
    transTint = m.transmission_color.rgb;
    transIor = (m.transmission_ior > 0.0) ? m.transmission_ior : matIor;
    emissive  = m.emissive_color.rgb * m.emissive_color.a;
    ao        = m.occlusion;
    opacityThreshold = m.opacity_threshold;
    opacityThresholdActive = (opacityThreshold > 0.0) ? 1 : 0;
    useSpecularWorkflow = m.use_specular_workflow;
    specularColor = m.specular_color.rgb;
    int diffuse_tex = m.tex_indices_a.x;
    if (diffuse_tex >= 0) {
        vec4 t = texture(matTextures[nonuniformEXT(diffuse_tex)], tc);
        albedo *= t.rgb;
        alpha *= t.a;
    }
        /* Roughness from .g channel (ORM convention: G=Roughness). */
    int rough_tex = m.tex_indices_a.z;
    if (rough_tex >= 0) {
        float roughSample = texture(matTextures[nonuniformEXT(rough_tex)], tc).g;
        float roughScale = (m.roughness_tex_scale != 0.0) ? m.roughness_tex_scale : 1.0;
        roughness = roughSample * roughScale + m.roughness_tex_bias;
    }
    /* Metallic from .b channel (ORM convention: B=Metallic). */
    int metal_tex = m.tex_indices_a.w;
    if (metal_tex >= 0) {
        metallic = texture(matTextures[nonuniformEXT(metal_tex)], tc).b;
    }
        /* Normal-map perturbation, matching raytrace.rchit.glsl's
         * geometric-ONB approach. NormalsTextureBiasAndScale relies on
         * the (scale, bias) UsdUVTexture inputs to drive bump strength
         * — defaults of (2,2,2,1)/(-1,-1,-1,0) reproduce the implicit
         * `nm = nm * 2 - 1` mapping. */
    int normal_tex = m.tex_indices_a.y;
    if (normal_tex >= 0) {
        vec3 nm = texture(matTextures[nonuniformEXT(normal_tex)], tc).rgb;
        nm = nm * m.normal_tex_scale.rgb + m.normal_tex_bias.rgb;
        vec3 T, B;
        branchlessONB(N, T, B);
            N = normalize(T * nm.x * m.normal_scale
                        + B * nm.y * m.normal_scale
                        + N * nm.z);
        }
        /* Emissive: emissive_color * intensity, with optional texture. */
    int emissive_tex_idx = m.tex_indices_b.x;
    if (emissive_tex_idx >= 0) {
        vec3 etex = texture(matTextures[nonuniformEXT(emissive_tex_idx)], tc).rgb;
            if (dot(emissive, emissive) < 0.001) {
                /* Constant emissive is black — texture IS the emissive color. */
                emissive = etex * m.emissive_color.a;
            } else {
                emissive *= etex;
            }
        }
        /* AO from .r channel (ORM convention: R=AO). */
    int ao_tex = m.tex_indices_b.y;
    if (ao_tex >= 0) {
        ao = texture(matTextures[nonuniformEXT(ao_tex)], tc).r;
    }
    int opacity_tex = m.tex_indices_b.z;
    if (opacity_tex >= 0) {
        vec4 opa = texture(matTextures[nonuniformEXT(opacity_tex)], tc);
        alpha *= (opa.r < 1.0) ? opa.r : opa.a;
    }
    int trans_tex = m.tex_transmission_weight;
    if (trans_tex >= 0) {
        transWeight *= texture(matTextures[nonuniformEXT(trans_tex)], tc).r;
    }
    sssWeight = m.subsurface_weight;
    int sss_tex = m.tex_subsurface_weight;
    if (sss_tex >= 0) {
        sssWeight *= texture(matTextures[nonuniformEXT(sss_tex)], tc).r;
    }
    sssWeight = clamp(sssWeight, 0.0, 1.0);
    sssColor = (m.sss_color_authored != 0) ? m.subsurface_color.rgb : albedo;
}

roughness = clamp(roughness, 0.04, 1.0);
if (opacityThresholdActive != 0 && alpha < opacityThreshold) {
    discard;
}
if (opacityThresholdActive != 0) {
    alpha = 1.0;
}

vec3 ptexColor = ptexTriangleColor(floatBitsToUint(pc.color.w));
if (ptexColor.x >= 0.0) {
    albedo = ptexColor;
}

/* ---- Cook-Torrance PBR setup ---- */
vec3 V = normalize(fragEyePos - fragWorldPos);
if (dot(N, V) < 0.0) {
    N = -N;
}

bool has_ibl = pc.ibl_params.x > 0.5;
bool has_fallback_lighting = has_ibl && pc.ibl_params.z < -1.0;
float NdotV = max(dot(N, V), 0.001);
bool hasSceneLights = sceneLights.nlights > 0;
bool manyAuthoredLightNoIbl = !has_ibl && pc.ibl_params.z < -2.5;
bool useSceneLights = hasSceneLights;
bool manySceneLightsWithIbl = has_ibl && useSceneLights && sceneLights.nlights > 8;
bool authoredKeyOnlyNoIbl = !has_ibl && hasSceneLights &&
                            pc.ibl_params.z < -1.0 &&
                            sceneLights.nlights <= 8;
bool authoredLightNoIbl = !has_ibl && pc.ibl_params.z < -1.0 && !useSceneLights;
bool noLightNoIbl = !has_ibl && !hasSceneLights && !authoredLightNoIbl;
bool displayColorFallback = ((!has_ibl || has_fallback_lighting) && materialUsesVertexColor);
if (displayColorFallback) {
    albedo = clamp(albedo * vec3(1.030, 1.012, 0.965), vec3(0.0), vec3(1.0));
}
float displayAmbientOcclusion = 1.0;
float displayDirectOcclusion = 1.0;
float displayBrightBoost = 1.0;
if (displayColorFallback) {
    float displayAlbedoLuma = dot(albedo, vec3(0.2126, 0.7152, 0.0722));
    float displayUp = abs(N.z);
    float displayAbsUp = abs(N.z);
    float upFace = smoothstep(0.30, 0.85, displayUp);
    float lowSurface = 1.0 - smoothstep(8.0, 60.0, fragWorldPos.z);
    float darkUp = upFace * lowSurface;
    float brightUp = upFace * (1.0 - lowSurface) * smoothstep(0.50, 0.88, displayAlbedoLuma);
    float verticalFace = 1.0 - smoothstep(0.18, 0.95, displayAbsUp);
    float grazingFace = 1.0 - smoothstep(0.12, 0.58, NdotV);
    displayAmbientOcclusion = clamp(1.0 - 0.05 * verticalFace -
                                    0.04 * grazingFace -
                                    0.75 * darkUp,
                                    0.25, 1.0);
    displayDirectOcclusion = clamp(1.0 - 0.70 * darkUp, 0.30, 1.0);
    displayBrightBoost = 1.0 + 0.10 * brightUp;
}

/* IOR-driven dielectric F0, matching the RT shader / MaterialX standard
 * surface. The specular workflow is artist-authored F0 and disables the
 * metallic diffuse cancellation, same as raytrace.rchit.glsl. */
float f0_dielectric = pow((matIor - 1.0) / (matIor + 1.0), 2.0);
vec3 F0;
if (useSpecularWorkflow != 0) {
    metallic = 0.0;
    F0 = specularColor;
} else {
    F0 = mix(vec3(f0_dielectric), albedo, metallic);
}

/* ---- Direct lighting ----
 * When an HDR DomeLight is authored, ovrtx and the RT shader use that
 * IBL as the illumination source rather than adding a hidden raster key
 * light. Keep synthetic lights only for legacy no-IBL scenes and for
 * renderer-authored fallback IBL on otherwise unlit stages. */
vec3 Lo = vec3(0.0);
if ((!has_ibl || has_fallback_lighting) && !useSceneLights) {
    /* nanousdview's OVRTX no-light fallback is camera-attached. Use a
     * headlight-style key here so raw unlit assets match that app path. */
    vec3 keyDir = V;
    vec3  L = keyDir;
        vec3  H = normalize(V + L);
        float NdotL = max(dot(N, L), 0.0);
        if (NdotL > 0.0) {
            float D = distributionGGX(N, H, roughness);
            float G = geometrySmithSchlick(N, V, L, roughness);
            vec3  F = fresnelSchlickRoughness(max(dot(H, V), 0.0), F0, roughness);
            vec3  spec = (D * G * F) /
                         (4.0 * NdotV * NdotL + 1e-4);
            vec3  kS = F;
            vec3  kD = (vec3(1.0) - kS) * (1.0 - metallic);
        float keyIntensity = displayColorFallback ? 0.64 : 0.70;
        float keyVisibility = 1.0;
        if (authoredLightNoIbl && pc.ibl_params.w > 0.25) {
            keyVisibility = traceContactVisibility(fragWorldPos + N * 0.01,
                                                   L, 100000.0);
        }
        Lo += (kD * albedo / 3.14159265 + spec) *
              vec3(1.0, 0.95, 0.85) * keyIntensity * NdotL * keyVisibility;
    }

    /* Weak dome-like fill, matching OVRTX's small fallback DomeLight. */
    vec3 fillDir = vec3(0.0, 0.0, 1.0);
    float fillIntensity = authoredLightNoIbl ? 0.0 : (displayColorFallback ? 0.05 : 0.06);
    Lo += albedo * vec3(0.7, 0.8, 1.0) * fillIntensity
          * max(dot(N, fillDir), 0.0);
    if (displayColorFallback) {
        Lo *= displayDirectOcclusion * displayBrightBoost;
    }
}

if (useSceneLights) {
    int nlights = min(sceneLights.nlights, 128);
    for (int li = 0; li < nlights; ++li) {
        Lo += evalSceneLight(sceneLights.items[li], N, V, albedo, metallic,
                             roughness, F0, fragWorldPos, NdotV);
    }
}

    /* ---- Ambient — IBL when env loaded, procedural hemisphere otherwise --- */
    vec3 ambientTerm;
    if (has_ibl) {
        /* Match raytrace.rchit.glsl's ovrtx-oriented IBL approximation:
         * SH irradiance for diffuse, GGX-prefiltered env for glossy
         * reflection, and the precomputed split-sum BRDF LUT. */
        vec3 R = reflect(-V, N);
        vec3 irradiance = texture(irrMap, dirToEquirect(N)).rgb;
        vec3 kS_ibl = fresnelSchlickRoughness(NdotV, F0, roughness);
        vec3 kD_ibl = (vec3(1.0) - kS_ibl) * (1.0 - metallic);
        vec3 diffuseAlbedo = (sssWeight > 0.0)
                            ? mix(albedo, sssColor, sssWeight)
                            : albedo;
        vec3 diffuseIBL = kD_ibl * irradiance * (diffuseAlbedo / 3.14159265);
        float upFacing = smoothstep(0.0, 0.85, clamp(N.z, 0.0, 1.0));
        float albedoLum = dot(albedo, vec3(0.2126, 0.7152, 0.0722));
        float darkVertical = mix(0.08, 1.0, smoothstep(0.28, 0.60, albedoLum));
        float diffuseShape = mix(darkVertical, 1.42, upFacing);
        float specularShape = mix(0.08, 1.0, upFacing);
        float verticalOcc = 1.0 - smoothstep(0.18, 0.90, abs(N.z));
        float lowOcc = 1.0 - smoothstep(0.015, 0.145, fragWorldPos.z);
        float darkOcc = 1.0 - smoothstep(0.10, 0.55, albedoLum);
        float localOcc = clamp(1.0 - verticalOcc *
                               (0.24 + 0.32 * lowOcc + 0.24 * darkOcc),
                               0.35, 1.0);
        diffuseIBL *= diffuseShape;

        float lod = roughness * max(pc.ibl_params.y - 1.0, 0.0);
        vec3 prefiltered = textureLod(envMap, dirToEquirect(R), lod).rgb;
        vec3 specularIBL = prefiltered * sampleEnvBRDF(F0, roughness, NdotV);
        specularIBL *= specularShape;
        if (manySceneLightsWithIbl) {
            /* Large Isaac-style interiors use practical fixtures plus a flat
             * DomeLight. Match OVRTX by keeping ceiling fill low while giving
             * low upward floors the bounce that the flat IBL otherwise lacks. */
            float highInterior = smoothstep(1.0, 3.0, fragWorldPos.z);
            float lowFloor = smoothstep(0.15, 0.85, clamp(N.z, 0.0, 1.0)) *
                             (1.0 - smoothstep(0.05, 0.50, fragWorldPos.z));
            float downwardFace = smoothstep(0.12, 0.72, clamp(-N.z, 0.0, 1.0));
            float verticalFace = 1.0 - smoothstep(0.18, 0.90, abs(N.z));
            float ceilingFace = highInterior * downwardFace * (1.0 - lowFloor);
            float upperVertical = highInterior * verticalFace * (1.0 - lowFloor);
            diffuseIBL *= mix(1.0, 0.12, max(ceilingFace, upperVertical * 0.18));
            specularIBL *= mix(1.0, 0.20, ceilingFace);
            localOcc *= mix(1.0, 0.74, ceilingFace);
        }
        float contact = 1.0;
        if (pc.ibl_params.w > 0.25)
            contact = mix(0.30, 1.0, contactVisibility(fragWorldPos, N));
        ambientTerm = (diffuseIBL + specularIBL) * ao * contact * localOcc;
        float coolBounce = upFacing * (1.0 - metallic) *
                           smoothstep(0.06, 0.45, albedoLum);
        ambientTerm += vec3(0.025, 0.040, 0.065) *
                       coolBounce * ao * contact;
        float lowHorizontal = upFacing * (1.0 - metallic) *
                              (1.0 - smoothstep(0.006, 0.035, fragWorldPos.z)) *
                              smoothstep(0.06, 0.42, albedoLum);
        ambientTerm += vec3(0.040, 0.070, 0.120) *
                       lowHorizontal * ao * contact;

        if (sssWeight > 0.0) {
            vec3 backIrradiance = texture(irrMap, dirToEquirect(-N)).rgb;
            ambientTerm += backIrradiance * (sssColor / 3.14159265)
                         * sssWeight * 0.2 * ao * localOcc * (1.0 - metallic);
        }

        /* Shadow mode (NU_RENDER_SHADOW): trace a ray query in the
         * surface-normal direction and darken the diffuse half of the
         * ambient contribution when occluded. Without this every
         * chess piece face that sees the dome ends up at full IBL,
         * making marble pieces look like polished chrome (the user's
         * "shiny metal" complaint). pc.ibl_params.w is the shadow
         * gate — renderer.c sets it to 1.0 only in NU_RENDER_SHADOW.
         * The reflection vector R is also tested for the specular
         * term so ray-occluded reflections fall to roughly the
         * surface diffuse. */
        if (pc.ibl_params.w > 0.5) {
            vec3 origin = fragWorldPos + N * 0.001;
            float diffShadow = 1.0;
            {
                if (traceContactVisibility(origin, N, 5.0) < 0.5)
                    diffShadow = 0.12;
            }
            float specShadow = 1.0;
            {
                if (traceContactVisibility(origin, R, 5.0) < 0.5)
                    specShadow = 0.12;
            }
            ambientTerm = (diffuseIBL * diffShadow +
                           specularIBL * specShadow) * ao * contact * localOcc;
            if (sssWeight > 0.0) {
                vec3 backIrradiance = texture(irrMap, dirToEquirect(-N)).rgb;
                ambientTerm += backIrradiance * (sssColor / 3.14159265)
                             * sssWeight * 0.2 * ao * contact
                             * localOcc * (1.0 - metallic);
            }
        }
    } else {
        /* Procedural sky/ground hemisphere — preserves chess and other
         * pre-IBL scenes bit-stable. Original parity-tuned constants. */
        vec3 skyColor    = vec3(0.50, 0.58, 0.75);
        vec3 groundColor = vec3(0.22, 0.20, 0.17);
        float hemi = dot(N, vec3(0.0, 0.0, 1.0)) * 0.5 + 0.5;
        vec3 ambient = mix(groundColor, skyColor, hemi) + vec3(0.08, 0.08, 0.10);
        vec3 kS_amb = fresnelSchlick(NdotV, F0);
        vec3 kD_amb = (vec3(1.0) - kS_amb) * (1.0 - metallic);
        vec3 diffuseAlbedo = (sssWeight > 0.0)
                            ? mix(albedo, sssColor, sssWeight)
                            : albedo;
        ambientTerm = (kD_amb * ambient * diffuseAlbedo + kS_amb * ambient * 0.06) * ao;
        float skyUp = clamp(N.z, 0.0, 1.0);
        vec3 skyFillColor = manyAuthoredLightNoIbl
                           ? vec3(0.024, 0.030, 0.034)
                           : vec3(0.018, 0.030, 0.055);
        ambientTerm += skyFillColor * skyUp * ao * (1.0 - metallic);
        if (manyAuthoredLightNoIbl) {
            float lowSceneHorizontal = smoothstep(0.15, 0.85, skyUp) *
                                       (1.0 - smoothstep(0.05, 0.45, fragWorldPos.z));
            ambientTerm *= mix(0.35, 1.0, lowSceneHorizontal);
            ambientTerm += vec3(0.058, 0.066, 0.074) *
                           lowSceneHorizontal * ao * (1.0 - metallic);
        }
        if (authoredLightNoIbl) {
            ambientTerm *= 0.35;
            if (pc.ibl_params.w > 0.25) {
                float contact = contactVisibility(fragWorldPos, N);
                ambientTerm *= mix(0.58, 1.0, contact);
            }
        }
        if (displayColorFallback) {
            ambientTerm *= displayAmbientOcclusion * displayBrightBoost;
        }
    }
    if (authoredKeyOnlyNoIbl) {
        ambientTerm = vec3(0.0);
    }

    /* Final color. The IBL branch uses the same intensity-tracking
     * exposure curve as raytrace.rchit.glsl so authored DomeLight
     * intensity affects raster surfaces in the same direction as ovrtx
     * without multiplying raw HDR intensity straight into every BRDF. */
    vec3 color = ambientTerm + Lo + emissive;
    if (manySceneLightsWithIbl) {
        float highInterior = smoothstep(1.0, 3.0, fragWorldPos.z);
        float lowFloor = smoothstep(0.15, 0.85, clamp(N.z, 0.0, 1.0)) *
                         (1.0 - smoothstep(0.05, 0.50, fragWorldPos.z));
        float downwardFace = smoothstep(0.12, 0.72, clamp(-N.z, 0.0, 1.0));
        float verticalFace = 1.0 - smoothstep(0.18, 0.90, abs(N.z));
        float ceilingFace = highInterior * downwardFace * (1.0 - lowFloor);
        float upperVertical = highInterior * verticalFace * (1.0 - lowFloor);
        float interiorScale = mix(1.0, 0.10, ceilingFace) *
                              mix(1.0, 0.82, upperVertical);
        vec3 floorLift = mix(vec3(1.0), vec3(4.02, 4.22, 4.42), lowFloor);
        color = (ambientTerm + Lo) * interiorScale * floorLift + emissive;
    }
    if (manyAuthoredLightNoIbl) {
        float floorShape = smoothstep(0.15, 0.85, clamp(N.z, 0.0, 1.0)) *
                           (1.0 - smoothstep(0.05, 0.45, fragWorldPos.z));
        float highInterior = smoothstep(1.2, 3.0, fragWorldPos.z);
        float nonFloorScale = mix(0.40, 0.16, highInterior);
        color *= mix(nonFloorScale, 1.0, floorShape);
    }
    if (authoredLightNoIbl) {
        color *= vec3(0.32, 0.14, 0.045);
    }
    if (noLightNoIbl) {
        color *= vec3(1.16, 0.98, 0.78);
    }
    /* Raster transmission is only an approximation: sampling the raw dome
     * through alpha-blended materials makes the chess glass read much
     * brighter than both ovrtx and OpenGL. Treat authored transmission as
     * the control here; alpha still drives cutout/coverage, not IBL-through
     * lighting. */
    float transmissionMix = clamp(transWeight * 0.18, 0.0, 1.0);
    if (has_ibl && transmissionMix > 0.001) {
        bool clearGlass = (transTint.r > 0.95 &&
                           transTint.g > 0.95 &&
                           transTint.b > 0.95);
        vec3 rayDir = -V;
        bool entering = dot(rayDir, N) < 0.0;
        vec3 Nr = entering ? N : -N;
        float eta = entering ? (1.0 / max(transIor, 1.001)) : max(transIor, 1.001);
        vec3 throughDir;
        if (clearGlass) {
            vec3 T = refract(rayDir, Nr, eta);
            throughDir = (dot(T, T) < 1e-6) ? reflect(rayDir, Nr) : T;
        } else {
            throughDir = rayDir;
        }
        vec3 R = reflect(rayDir, N);
        vec3 transmitted = textureLod(envMap, dirToEquirect(throughDir), 0.0).rgb;
        if (transWeight > 0.001) transmitted *= transTint;
        if (alpha < 0.5)         transmitted *= albedo;
        vec3 reflected = textureLod(envMap, dirToEquirect(R), 0.0).rgb;
        float f0Glass = pow((transIor - 1.0) / (transIor + 1.0), 2.0);
        float fresnel = f0Glass + (1.0 - f0Glass) * pow(1.0 - clamp(NdotV, 0.0, 1.0), 5.0);
        vec3 glassColor = mix(transmitted, reflected, fresnel);
        color = mix(color, glassColor, transmissionMix);
    }

    if (clearcoat > 0.0 && transmissionMix <= 0.001 && !has_ibl) {
        vec3 ccL = normalize(vec3(0.3, 1.0, 0.5));
        vec3 ccH = normalize(V + ccL);
        float ccNdotL = max(dot(N, ccL), 0.0);
        float ccD = distributionGGX(N, ccH, clearcoatRoughness);
        float ccG = geometrySmithSchlick(N, V, ccL, clearcoatRoughness);
        vec3  ccF = fresnelSchlick(max(dot(ccH, V), 0.0), vec3(0.04));
        vec3  ccSpec = (ccD * ccG * ccF) / (4.0 * NdotV * ccNdotL + 0.0001);
        color += ccSpec * vec3(1.0, 0.95, 0.85) * ccNdotL * clearcoat;
    } else if (clearcoat > 0.0 && transmissionMix <= 0.001 && has_ibl) {
        vec3 ccR = reflect(-V, N);
        float ccLod = clearcoatRoughness * max(pc.ibl_params.y - 1.0, 0.0);
        vec3 ccEnv = textureLod(envMap, dirToEquirect(ccR), ccLod).rgb;
        vec3 ccF = fresnelSchlick(NdotV, vec3(0.04));
        float upFacing = smoothstep(0.0, 0.85, clamp(N.z, 0.0, 1.0));
        float specularShape = mix(0.08, 1.0, upFacing);
        color += ccEnv * ccF * clearcoat * specularShape;
    }

    float exposure;
    if (has_ibl) {
        float intensity = (pc.ibl_params.z < -1.0) ? 1.0 : abs(pc.ibl_params.z);
        float t1 = clamp(log(1.0 + intensity) / log(1001.0), 0.0, 1.25);
        float gate = smoothstep(1.0, 2.0, intensity);
        float boost1 = 1.0 + 0.4 * t1 * gate;
        float boost2 = pow(max(intensity / 1000.0, 1.0), 0.85);
        /* Large Isaac-style interiors ship many authored fixtures plus a
         * textureless DomeLight IBL. OVRTX auto-exposes that combination much
         * darker than the chess two-light IBL rig, so keep the correction scoped
         * to many-light IBL scenes. */
        float manyLightIblScale = manySceneLightsWithIbl ? 0.28 : 1.0;
        exposure = 0.12 * boost1 * boost2 * manyLightIblScale;
    } else if (useSceneLights) {
        /* OVRTX's camera exposure for authored RectLight-only probe scenes
         * is much lower than the legacy no-IBL raster fallback. Using the
         * old 1.2 exposure after enabling scene lights washed out GB300's
         * painted-metal side panels. Many-light no-HDR scenes such as Isaac
         * warehouse need a lower exposure because the raster path still lacks
         * OVRTX's full light selection, shadowing, and normalization. */
        exposure = 0.30;
    } else {
        exposure = displayColorFallback ? 0.54 : (noLightNoIbl ? 0.20 : 0.72);
    }
    color = acesFilmic(color * exposure * max(pc.tone_params.x, 0.0));
    color = pow(color, vec3(1.0 / 2.2));


    outColor = vec4(color, 1.0);
}
