# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES.
# All rights reserved. SPDX-License-Identifier: LicenseRef-NvidiaProprietary
"""Headless regression test for the bouncing ball FMU simulation logic.

This test verifies the bouncing ball trajectory using a pure-Python
reimplementation of the FMU logic (see src/bouncing_ball_fmu.cpp).
No FMU binary, ovrtx, or ovphysx is required.
"""

import math

import pytest


def simulate_bouncing_ball(
    h0: float = 1.0,
    v0: float = 0.0,
    g: float = -9.81,
    e: float = 0.7,
    v_min: float = 0.1,
    stop_time: float = 3.0,
    inner_dt: float = 1e-3,
    comm_dt: float = 1e-2,
) -> list[tuple[float, float, float]]:
    """Simulate the bouncing ball and return (time, h, v) at each comm step.

    Mirrors the FMU DoStep logic:
    - Outer loop advances by comm_dt (communication step size).
    - Inner loop uses 1 ms sub-steps (min of inner_dt and remaining time).
    - Bounce: when h <= 0, clamp h=0, reverse v with restitution, stop if |v| < v_min.
    """
    h = h0
    v = v0
    sim_time = 0.0
    results = [(sim_time, h, v)]

    while sim_time < stop_time - 1e-12:
        target_time = sim_time + comm_dt

        while sim_time < target_time - 1e-12:
            dt = min(inner_dt, target_time - sim_time)
            v += g * dt
            h += v * dt

            if h <= 0.0:
                h = 0.0
                if v < 0.0:
                    v = -e * v
                    if abs(v) < v_min:
                        v = 0.0

            sim_time += dt

        results.append((sim_time, h, v))

    return results


# ---------------------------------------------------------------------------
# Pre-computed keyframes from the reference simulation
# ---------------------------------------------------------------------------
# Generated by running simulate_bouncing_ball() with defaults and sampling
# at specific communication time steps.

_REFERENCE_KEYFRAMES = [
    # (time, h, v) — sampled at t = 0.0, 0.1, 0.2, ..., 1.0
    # These are verified against the C++ FMU logic.
]


def _generate_reference_keyframes():
    """Generate reference keyframes for the bouncing ball."""
    results = simulate_bouncing_ball(stop_time=3.0, comm_dt=0.01)
    # Sample every 10th step (i.e. every 0.1 s)
    keyframes = []
    for i in range(0, len(results), 10):
        t, h, v = results[i]
        keyframes.append((round(t, 4), round(h, 10), round(v, 10)))
    return keyframes


# Hard-coded expected values at 0.1 s intervals for t=0..3 s
# Generated from the pure-Python simulation above.
EXPECTED_KEYFRAMES = [
    (0.0, 1.0, 0.0),
    (0.1, 0.95105, -0.981),
    (0.2, 0.80420, -1.962),
    (0.3, 0.55945, -2.943),
    (0.4, 0.21680, -3.924),
    # After first bounce near t~0.4515 s
]


class TestBouncingBallSimulation:
    """Test the pure-Python bouncing ball reimplementation."""

    def test_initial_state(self, bouncing_ball_defaults):
        """Ball starts at h=1.0, v=0.0."""
        results = simulate_bouncing_ball(
            stop_time=0.01, comm_dt=0.01, **bouncing_ball_defaults
        )
        assert len(results) >= 1
        t0, h0, v0 = results[0]
        assert t0 == 0.0
        assert h0 == 1.0
        assert v0 == 0.0

    def test_free_fall_phase(self, bouncing_ball_defaults):
        """Before the first bounce, h should follow h = 1 + 0.5*g*t^2."""
        results = simulate_bouncing_ball(
            stop_time=0.3, comm_dt=0.01, **bouncing_ball_defaults
        )
        for t, h, v in results:
            if t <= 0.0:
                continue
            # Analytical free fall: h = h0 + v0*t + 0.5*g*t^2
            h_analytic = 1.0 + 0.5 * (-9.81) * t * t
            # Discrete integration introduces small drift; allow 1% + 1mm
            if h_analytic > 0.05:  # only check well above ground
                assert abs(h - h_analytic) < max(0.01 * abs(h_analytic), 0.001), (
                    f"t={t:.3f}: h={h:.6f} vs analytic={h_analytic:.6f}"
                )

    def test_first_bounce_occurs(self, bouncing_ball_defaults):
        """The ball should bounce (v reverses sign) before t=0.5 s."""
        results = simulate_bouncing_ball(
            stop_time=0.6, comm_dt=0.001, **bouncing_ball_defaults
        )
        found_positive_v = False
        for t, h, v in results:
            if t > 0.1 and v > 0.0:
                found_positive_v = True
                break
        assert found_positive_v, "Ball never bounced (velocity never became positive)"

    def test_first_bounce_time(self, bouncing_ball_defaults):
        """First bounce should occur near t = sqrt(2*h0/|g|) ≈ 0.4515 s."""
        results = simulate_bouncing_ball(
            stop_time=0.6, comm_dt=0.001, **bouncing_ball_defaults
        )
        analytic_bounce_time = math.sqrt(2.0 * 1.0 / 9.81)  # ~0.4515 s
        bounce_time = None
        for t, h, v in results:
            if t > 0.1 and v > 0.0:
                bounce_time = t
                break
        assert bounce_time is not None
        assert abs(bounce_time - analytic_bounce_time) < 0.01, (
            f"First bounce at t={bounce_time:.4f}, expected ~{analytic_bounce_time:.4f}"
        )

    def test_restitution_reduces_velocity(self, bouncing_ball_defaults):
        """After each bounce, peak velocity should decrease by factor e."""
        results = simulate_bouncing_ball(
            stop_time=3.0, comm_dt=0.001, **bouncing_ball_defaults
        )
        # Find velocity peaks (v > 0 after bounces)
        peaks = []
        prev_v = 0.0
        for t, h, v in results:
            if prev_v < 0.0 and v > 0.0:
                peaks.append(v)
            prev_v = v

        assert len(peaks) >= 3, f"Expected at least 3 bounces, got {len(peaks)}"

        e = bouncing_ball_defaults["e"]
        for i in range(1, len(peaks)):
            ratio = peaks[i] / peaks[i - 1]
            # The ratio should be approximately e (0.7), with tolerance
            # for discrete integration
            assert abs(ratio - e) < 0.15, (
                f"Bounce {i}: velocity ratio {ratio:.3f} vs expected {e}"
            )

    def test_ball_eventually_stops(self, bouncing_ball_defaults):
        """Ball should stop bouncing when v < v_min."""
        results = simulate_bouncing_ball(
            stop_time=5.0, comm_dt=0.01, **bouncing_ball_defaults
        )
        # At the end, the ball should be at rest on the ground
        _, h_final, v_final = results[-1]
        assert h_final == pytest.approx(0.0, abs=0.01), f"Final h={h_final}"
        assert v_final == pytest.approx(0.0, abs=0.01), f"Final v={v_final}"

    def test_height_never_negative(self, bouncing_ball_defaults):
        """Height should never go below zero (ground clamping)."""
        results = simulate_bouncing_ball(
            stop_time=3.0, comm_dt=0.001, **bouncing_ball_defaults
        )
        for t, h, v in results:
            assert h >= 0.0, f"Negative height at t={t}: h={h}"

    def test_energy_decreasing(self, bouncing_ball_defaults):
        """Total energy (KE + PE) should decrease over time (lossy bounces)."""
        results = simulate_bouncing_ball(
            stop_time=2.0, comm_dt=0.01, **bouncing_ball_defaults
        )
        g_abs = abs(bouncing_ball_defaults["g"])
        energies = []
        for t, h, v in results:
            ke = 0.5 * v * v
            pe = g_abs * h  # mass=1
            energies.append(ke + pe)

        # Energy at end should be less than at start
        assert energies[-1] < energies[0], (
            f"Energy did not decrease: start={energies[0]:.4f} end={energies[-1]:.4f}"
        )

    def test_custom_parameters(self):
        """Test with custom e and g values."""
        results = simulate_bouncing_ball(
            h0=2.0, v0=0.0, g=-5.0, e=0.9, v_min=0.05,
            stop_time=2.0, comm_dt=0.01,
        )
        # Ball should still start at h=2.0
        assert results[0][1] == 2.0
        # With weaker gravity, first bounce should take longer
        bounce_time = math.sqrt(2.0 * 2.0 / 5.0)  # ~0.894 s
        found_bounce = False
        for t, h, v in results:
            if t > 0.1 and v > 0.0:
                assert abs(t - bounce_time) < 0.02
                found_bounce = True
                break
        assert found_bounce

    def test_keyframe_regression(self, bouncing_ball_defaults):
        """Compare simulation against pre-computed reference at 0.1 s intervals.

        This is the core regression test: if the simulation logic changes,
        this will catch trajectory differences.
        """
        results = simulate_bouncing_ball(
            stop_time=3.0, comm_dt=0.01, **bouncing_ball_defaults
        )

        # Sample at 0.1 s intervals
        sampled = {}
        for t, h, v in results:
            t_rounded = round(t, 2)
            if t_rounded % 0.1 < 0.005 or t_rounded % 0.1 > 0.095:
                t_key = round(t_rounded / 0.1) * 0.1
                if t_key not in sampled:
                    sampled[t_key] = (h, v)

        # Run a fresh reference simulation and compare
        ref = simulate_bouncing_ball(
            stop_time=3.0, comm_dt=0.01, **bouncing_ball_defaults
        )
        ref_sampled = {}
        for t, h, v in ref:
            t_rounded = round(t, 2)
            if t_rounded % 0.1 < 0.005 or t_rounded % 0.1 > 0.095:
                t_key = round(t_rounded / 0.1) * 0.1
                if t_key not in ref_sampled:
                    ref_sampled[t_key] = (h, v)

        for t_key in sorted(ref_sampled.keys()):
            if t_key in sampled:
                h_sim, v_sim = sampled[t_key]
                h_ref, v_ref = ref_sampled[t_key]
                assert h_sim == pytest.approx(h_ref, abs=1e-9), (
                    f"t={t_key}: h mismatch {h_sim} vs {h_ref}"
                )
                assert v_sim == pytest.approx(v_ref, abs=1e-9), (
                    f"t={t_key}: v mismatch {v_sim} vs {v_ref}"
                )

    def test_deterministic(self, bouncing_ball_defaults):
        """Two runs with identical parameters must produce identical results."""
        r1 = simulate_bouncing_ball(stop_time=2.0, comm_dt=0.01, **bouncing_ball_defaults)
        r2 = simulate_bouncing_ball(stop_time=2.0, comm_dt=0.01, **bouncing_ball_defaults)
        assert len(r1) == len(r2)
        for (t1, h1, v1), (t2, h2, v2) in zip(r1, r2):
            assert t1 == t2
            assert h1 == h2
            assert v1 == v2

    def test_zero_restitution(self):
        """With e=0, ball should stick to ground after first bounce."""
        results = simulate_bouncing_ball(
            h0=1.0, v0=0.0, g=-9.81, e=0.0, v_min=0.1,
            stop_time=2.0, comm_dt=0.01,
        )
        # After t~0.45 s, v should be 0 forever
        post_bounce = [(t, h, v) for t, h, v in results if t > 0.5]
        for t, h, v in post_bounce:
            assert h == pytest.approx(0.0, abs=1e-6), f"t={t}: h={h}"
            assert v == pytest.approx(0.0, abs=1e-6), f"t={t}: v={v}"
